sudo: false
language: php

php:
  - 5.6

before_install:
  - composer selfupdate
  - phpenv config-rm xdebug.ini

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - composer install

script:
  # Run for each changed file the code sniffer.
  - git diff --name-only $TRAVIS_COMMIT_RANGE | while read in; do ./vendor/bin/phpcs "$in"; done
